name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "news_now"
database_id = "82b565ec-821d-49fd-a82e-7d63e55f4997"
